### ISSUE TITLE
ImportError: cannot import name 'onnx_pb2'

### ISSUE THREAD

**Issue by gr8Adakron** [NVIDIA/mxnet_to_onnx#2]
While installing I am getting this error

`ERROR: Failure: ImportError (cannot import name 'onnx_pb2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/afzal/onnx_conversion/mxnet_to_onnx/tests/test_convert_lenet5.py", line 38, in <module>
    from mx2onnx_converter.conversion_helpers import from_mxnet
  File "/home/afzal/onnx_conversion/mxnet_to_onnx/mx2onnx_converter/__init__.py", line 29, in <module>
    import mx2onnx_converter.conversion_helpers
  File "/home/afzal/onnx_conversion/mxnet_to_onnx/mx2onnx_converter/conversion_helpers.py", line 33, in <module>
    from .mx2onnx_converter import MxNetToONNXConverter
  File "/home/afzal/onnx_conversion/mxnet_to_onnx/mx2onnx_converter/mx2onnx_converter.py", line 36, in <module>
    from onnx import (defs, checker, helper, numpy_helper, mapping, onnx_pb2,
ImportError: cannot import name 'onnx_pb2'
`

**## Details:**
Ubuntu: 16.06
python: 3.6
onnx==1.1.2
onnx-mxnet==0.4.0
mxnet==1.2.0

**Comment by mkolod** [comment]
This should be fixed now (please pull master with the latest commit). Sorry for a slow response.
